### PR TITLE
Adjust patch for VSCode 1.38.0

### LINKED ISSUE #38: Not working on 1.38
It seems that the last update broke some of the patches that this extension applies. I've checked the console output and it seems because some files don't exist anymore, in this case they seem to have been renamed

```javascript
[Extension Host] Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js'    at Object.openSync (fs.js:436:3)    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)    at Object.readFileSync (fs.js:341:35)    at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:580:40)    at applyPatches (/Users/alex/.vscode/extensions/lehni.vscode-titlebar-less-macos-1.9.1/extension.js:164:26)
```

```javascript
[Extension Host] Error: ENOENT: no such file or directory, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css'    at Object.openSync (fs.js:436:3)    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)    at Object.readFileSync (fs.js:341:35)    at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:580:40)    at applyPatches (/Users/alex/.vscode/extensions/lehni.vscode-titlebar-less-macos-1.9.1/extension.js:164:26)
```

It seems that the new files are called `workbench.desktop.main.js` and `workbench.desktop.main.css` respectively

### PR DESCRIPTION
**Pull request by dpren**
Fixes #38

### CODE REVIEW

**Comment by dpren** [comment]
This is just filenames so far - I plan to add an update for the layout.ts patch.

**Comment by lehni** [comment]
Hi @dpren. Thanks for this! I'm taking a look now. For the future: It would be good to do PRs in feature branches that we den merge to master. Thx!

**Comment by lehni** [comment]
This doesn't seem to fully work yet for me. Here's how it looks after applying with the traffic lights activated (which should still be the default setting):

Screenshot 2019-09-30 at 10 45 49

**Comment by lehni** [comment]
@dpren did you see my answer above? Am I misunderstanding something?

**Comment by dpren** [comment]
@lehni My apologies, I should have held off on the PR... I'm still working on updating the layout "replace" patch, but the new vs code is very different so it's taking longer than I thought.

**Comment by lehni** [comment]
Closing as the extension has been deprecated in favour of https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui

Read https://github.com/lehni/vscode-titlebar-less-macos/blob/master/README.md for details

**Pull request closed without merging**
