### PR TITLE
extension: Update patch targets filenames

### PR DESCRIPTION
**Pull request by aexvir**
Unfortunately, even with the patches fixed it still seems to not be working properly 😕 Tried multiple restards, as I saw in https://github.com/lehni/vscode-titlebar-less-macos/issues/36, but didn't help

Screen Shot 2019-09-04 at 23 47 44

### CODE REVIEW

**Comment by aexvir** [comment]
Got it "working" after messing with the CSS for a while, but dragging the window doesn't work for example. The DOM seems quite nested, and it seems to be setting the width in runtime, so it's tricky to get a selector with more specificity.

Screen Shot 2019-09-05 at 00 45 26

**Comment by aexvir** [comment]
I'll be waiting for your proper fix here, meanwhile I have it "working" with horrible CSS rules

**Comment by aexvir** [comment]
Related to #38

**Comment by lehni** [comment]
I will look into this as soon as I get the time to do so. I'm on a deadline for a project right now, so it may be 2-3 weeks.

**Comment by lehni** [comment]
Closing as the extension has been deprecated in favour of https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui

Read https://github.com/lehni/vscode-titlebar-less-macos/blob/master/README.md for details

**Pull request closed without merging**
